"""cambio de longitud del vector a 512

Revision ID: 9382f584012c
Revises: a55cc2c39e57
Create Date: 2026-05-02 22:04:54.488709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "9382f584012c"
down_revision: Union[str, Sequence[str], None] = "a55cc2c39e57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_faces",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_faces",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
